sudo: false
language: python
matrix:
  include:
    - python: "2.6"
      env: WITH_OPTIONAL_DEPS=no TEST_SPHINX=no
    - python: "2.6"
      env: WITH_OPTIONAL_DEPS=yes TEST_SPHINX=no
    - python: "2.7_with_system_site_packages"
      env: WITH_OPTIONAL_DEPS=no TEST_SPHINX=no
    - python: "2.7_with_system_site_packages"
      env: WITH_OPTIONAL_DEPS=yes TEST_SPHINX=yes
install:
  - testsuite/install.sh
  - pip install -e .
script:
  - nosetests testsuite
after_failure:
  - pip freeze
branches:
  except:
    - maint-1.2
    - 1.1.0-stable
notifications:
  email: chris.a.st.pierre@gmail.com
  irc:
    channels:
      - "irc.freenode.org#bcfg2"
    use_notice: true
addons:
  apt:
    packages:
      - swig
      - libxml2-utils
      - yum
      - libaugeas0
      - augeas-lenses
      - libacl1-dev
      - libssl-dev
      - python-gamin
      - python-selinux
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/xml
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
  - rm -f $HOME/.cache/xml/catalog.xml
